// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDN0KWWUJ-B98T0zHXL2Bis-cazFZRi00',
    appId: '1:204448318337:web:199877dc3f430623681e80',
    messagingSenderId: '204448318337',
    projectId: 'tic-tac-toe-xperience',
    authDomain: 'tic-tac-toe-xperience.firebaseapp.com',
    storageBucket: 'tic-tac-toe-xperience.appspot.com',
    measurementId: 'G-KGND4DRH4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5L5iq89Wropf8jkEfOX1sSsdiEYgjDDs',
    appId: '1:204448318337:android:eb2af6519b5d6538681e80',
    messagingSenderId: '204448318337',
    projectId: 'tic-tac-toe-xperience',
    storageBucket: 'tic-tac-toe-xperience.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmc7LzT8UgCF3GXRdi4H6wphp4MGatOII',
    appId: '1:204448318337:ios:a9b5b9e4f09b4b11681e80',
    messagingSenderId: '204448318337',
    projectId: 'tic-tac-toe-xperience',
    storageBucket: 'tic-tac-toe-xperience.appspot.com',
    iosClientId: '204448318337-j6pucpvhv8u2cve4p8r75kvfujcub04h.apps.googleusercontent.com',
    iosBundleId: 'com.freez.tictactoeMp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmc7LzT8UgCF3GXRdi4H6wphp4MGatOII',
    appId: '1:204448318337:ios:d37840a4634b4680681e80',
    messagingSenderId: '204448318337',
    projectId: 'tic-tac-toe-xperience',
    storageBucket: 'tic-tac-toe-xperience.appspot.com',
    iosClientId: '204448318337-rqe1nb8dalhcrhqr5lu927udlcdmnrce.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictactoeMp',
  );
}
